### ISSUE TITLE
Learn about how to edit this code

### ISSUE THREAD

**Issue by csouflis** [marcomaiermm/fastapi-postgres-vue-template#1]
Hi @marcomaiermm ,

Could you possibly recommend some resources on how to go about creating a repo like this? obviously I need to learn more fastapi and vue, but specific links would help me a lot. Thank you!

**Comment by marcomaiermm** [comment]
hey @csouflis , i would simply go to the official [fastapi documentation](https://fastapi.tiangolo.com/) and start creating your first API. From there, you could go and start learning how Docker and Docker-Compose works. Just look at a docker-compose file and start recreating your simple fastapi app in a docker container with compose. Then maybe add another container with a Vue application and start display stuff from your fastapi api. 

 Best thing is to stop watching tutorials and start creating stuff :). 

Install [Docker](https://docs.docker.com/engine/install/)
Install [Docker-Compose](https://docs.docker.com/compose/install/)

Nevertheless, a really good video/blog entry on Fastapi with traefik is the one from the creator of fastapi himself [https://dev.to/tiangolo/deploying-fastapi-and-other-apps-with-https-powered-by-traefik-5dik](https://dev.to/tiangolo/deploying-fastapi-and-other-apps-with-https-powered-by-traefik-5dik)
